name: ihostel
description: I Hostel
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.4 <4.0.0"

dependencies:
  animated_reorderable_list: ^1.1.1
  another_flushbar: ^1.12.30
  async: ^2.11.0
  audioplayers: ^6.0.0
  awesome_bottom_bar:
    path: ./flutter_libraries/awesome_bottom_bar
  bloc: ^8.1.2
  calendar_date_picker2: ^1.1.6
  collection: any
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  dio: ^5.5.0+1
  dropdown_button2: ^2.3.9
  email_validator: ^3.0.0
  encrypted_shared_preferences: 3.0.1
  firebase_analytics: ^10.10.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.31.0
  firebase_core_platform_interface: ^5.0.0
  firebase_crashlytics: ^3.5.5
  firebase_database: ^10.5.5
  firebase_messaging: ^14.9.2
  firebase_remote_config: ^4.4.5
  flutter:
    sdk: flutter
  flutter_bloc: any
  flutter_keyboard_visibility: ^5.4.1
  flutter_local_notifications: ^17.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_sizer: ^1.0.5
  flutter_svg: ^2.0.7
  flutter_timezone: ^1.0.8
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  full_calender: ^1.2.12
  get_it: ^7.6.4
  go_router: any
  google_sign_in: ^6.2.1
  image_cropper: ^8.0.1
  image_picker: ^1.1.2
  infinite_scroll_pagination: 4.0.0
  injectable: ^2.3.2
  intl: any
  intl_utils: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  keyboard_dismisser: ^3.0.0
  lottie: any
  math_expressions: ^2.4.0
  meta: any
  modal_bottom_sheet: ^3.0.0
  moment_dart: ^2.0.2
  package_info_plus: any
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.3.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  retrofit: ^4.1.0
  rxdart: 0.27.7
  scan: ^1.6.0
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^5.0.0
  skeletonizer: ^1.3.0
  sprintf: ^7.0.0
  syncfusion_flutter_xlsio: ^26.1.35
  table_calendar: ^3.0.9
  timezone: ^0.9.3
  ulid: ^2.0.0
  vibration: ^2.0.0




dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  go_router_builder: any
  injectable_generator: ^2.4.1
  isar_generator: ^3.1.0+1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mockito: ^5.4.2
  very_good_analysis: ^5.1.0

flutter_intl:
  enabled: true
  main_locale: vi
  output_dir: lib/l10n/generated
  arb_dir: lib/l10n
  synthetic-package: false
  nullable-getter: false
  format: true

flutter:
  generate: false
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
  assets:
    - assets/animations/
    - assets/fonts/Inter/OFL.txt
    - assets/images/
    - assets/audio/
flutter_gen:
  output: lib/assets_gen/
  line_length: 1000
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false